import type { NextPage } from 'next';
import Head from 'next/head';
import { useState, useMemo } from 'react';
import { encodeText } from '../utils/utils';
import { CONSONANTS } from '../utils/constants';
import SelectBox from '../components/SelectBox';

const Home: NextPage = () => {
  const [message, setMessage] = useState<string>('');
  const [encryptKey, setEncryptKey] = useState<number[]>([
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
  ]);
  const encryptedMessage = useMemo(() => {
    if (message.length > 0 && encryptKey)
      return encodeText(message, encryptKey);
    return message;
  }, [encryptKey, message]);

  const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    setMessage(event.currentTarget.value);
  };

  const handleChangeKey = (
    index: number,
    event: React.ChangeEvent<HTMLSelectElement>,
  ) => {
    const newKey = [...encryptKey];
    newKey[index] = Number(event.currentTarget.value);
    setEncryptKey(newKey);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="text-3xl font-bold underline">Hello World!</h1>
        <h2>Make your encryption key</h2>
        <div>
          {Array.from({ length: 19 }).map((_, index) => (
            <div key={index}>
              {CONSONANTS[index]}
              <SelectBox
                onChange={event => handleChangeKey(index, event)}
                defaultValue={index}
              />
            </div>
          ))}
        </div>
        <h2>Enter your message</h2>
        <textarea value={message} onChange={handleChange} />
        <div>{encryptedMessage}</div>
      </div>
    </div>
  );
};

export default Home;
